--------------------------------------------------------
--  File created - Monday-March-25-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DI_AUDIT_PSA03_DAC
--------------------------------------------------------

  CREATE TABLE "REPORTINTRA"."DI_AUDIT_PSA03_DAC" 
   (	"TRADE_NO" NUMBER, 
	"TRANSACTIONREF" VARCHAR2(200 BYTE), 
	"TRADEDATE" DATE, 
	"SELL_CODE" VARCHAR2(12 BYTE), 
	"SELLER_SID" VARCHAR2(20 BYTE), 
	"BUY_CODE" VARCHAR2(12 BYTE), 
	"BUYER_SID" VARCHAR2(20 BYTE), 
	"SEC_CODE" VARCHAR2(10 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER, 
	"MARKET_VALUE" NUMBER, 
	"LST_UPD_TS" CHAR(17 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTINTRA" ;
