--------------------------------------------------------
--  File created - Monday-March-25-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DI_AUDIT_PSA02_DAC
--------------------------------------------------------

  CREATE TABLE "REPORTINTRA"."DI_AUDIT_PSA02_DAC" 
   (	"REKENING_EFEK" VARCHAR2(100 BYTE), 
	"SID" VARCHAR2(20 BYTE), 
	"FULL_NAME" VARCHAR2(402 BYTE), 
	"BIRTH DATE" VARCHAR2(11 BYTE), 
	"NOMOR KTP" VARCHAR2(100 BYTE), 
	"NOMOR NPWP" VARCHAR2(100 BYTE), 
	"NOMOR PASSWORD" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MOBILE PHONE" VARCHAR2(60 BYTE), 
	"LOC_ASING" VARCHAR2(200 BYTE), 
	"NATIONALITY" VARCHAR2(100 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"POSTAL_CODE" VARCHAR2(10 BYTE), 
	"HOME PHONE" VARCHAR2(40 BYTE), 
	"OTHER_ADDR1" VARCHAR2(100 BYTE), 
	"OTHER_ADDR2" VARCHAR2(100 BYTE), 
	"OTHER_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"OTHER HOME PHONE" VARCHAR2(40 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"PROVINCE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"OTHER_CITY" VARCHAR2(100 BYTE), 
	"OTHER_PROVINCE" VARCHAR2(100 BYTE), 
	"OTHER_COUNTRY" VARCHAR2(100 BYTE), 
	"CORR_ADDR" VARCHAR2(13 BYTE), 
	"CREATE_DATE" VARCHAR2(11 BYTE), 
	"CREATION_STATUS" VARCHAR2(11 BYTE), 
	"USER STATUS" VARCHAR2(9 BYTE), 
	"ACCOUNT_STATUS" VARCHAR2(100 BYTE), 
	"CREATOR_CROSSLINK" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REPORTINTRA" ;
